### ISSUE TITLE
"Models aren't loaded yet"

### ISSUE THREAD

**Issue by platzhersh** [auto-mat/django-import-export-celery#19]
Following the instructions on how to setup exports, I am running into a "Models aren't loaded yet." error.

I added the Resource in the models.py file, but I have more than one app with models.py files.

The error is caused from the ResourceModel class defined at the very end of the models.py file.

This is the classmethod I added to the model:

    class Ride(models.Model):
        @classmethod
        def export_resource_classes(cls):
            return {
                'all rides': ('Ride resources', RideResource),
            }

this is the RideResource at the end of the file:

    class RideResource(ModelResource):
        class Meta:
            model = Ride

**Comment by platzhersh** [comment]
This is my error:


File "/path/to/project/models.py", line 400, in <module>
    class RideResource(ModelResource):
  File "/Users/chregiglatthard/GitHub/velafrica-django/.venv/lib/python3.6/site-packages/import_export/resources.py", line 779, in __new__
    readonly=False)
  File "/Users/chregiglatthard/GitHub/velafrica-django/.venv/lib/python3.6/site-packages/import_export/resources.py", line 927, in field_from_django_field
    FieldWidget = cls.widget_from_django_field(django_field)
  File "/Users/chregiglatthard/GitHub/velafrica-django/.venv/lib/python3.6/site-packages/import_export/resources.py", line 893, in widget_from_django_field
    result = getattr(cls, result)(f)
  File "/Users/chregiglatthard/GitHub/velafrica-django/.venv/lib/python3.6/site-packages/import_export/resources.py", line 873, in get_fk_widget
    model=get_related_model(field))
  File "/Users/chregiglatthard/GitHub/velafrica-django/.venv/lib/python3.6/site-packages/import_export/resources.py", line 47, in get_related_model
    if hasattr(field, 'related_model'):
  File "/Users/chregiglatthard/GitHub/velafrica-django/.venv/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/chregiglatthard/GitHub/velafrica-django/.venv/lib/python3.6/site-packages/django/db/models/fields/related.py", line 94, in related_model
    apps.check_models_ready()
  File "/Users/chregiglatthard/GitHub/velafrica-django/.venv/lib/python3.6/site-packages/django/apps/registry.py", line 137, in check_models_ready
    raise AppRegistryNotReady("Models aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.

**Comment by platzhersh** [comment]
And here is my celery.py:

```
from __future__ import absolute_import, unicode_literals

from __future__ import absolute_import, unicode_literals

import os

from celery import Celery
from django.conf import settings  # noqa

app = Celery('project',
             broker=settings.BROKER_URL,
             backend=settings.BROKER_URL)

# Optional configuration, see the application user guide.
app.conf.update(
    result_expires=3600,
)

# set the default Django settings module for the 'celery' program.
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "project.settings")

# Using a string here means the worker will not have to
# pickle the object when using Windows.
app.autodiscover_tasks(lambda: settings.INSTALLED_APPS)

if __name__ == '__main__':
    app.start()

```

**Comment by timthelion** [comment]
Is this error occuring on project launch or when you are in the admin?

**Comment by platzhersh** [comment]
It occurs when I try to start the project with `python manage.py runserver`

**Comment by platzhersh** [comment]
Any ideas? I know it could be my own code. But maybe you can reproduce it.

**Comment by timthelion** [comment]
Sorry I tried to look into it, but I'm not yet sure what's wrong. If you send me your code I can look better.

**Comment by platzhersh** [comment]
https://github.com/velafrica/velafrica-django/pull/87

**Comment by timthelion** [comment]
Is this resolved now? Or are you still having troubles?

**Comment by timthelion** [comment]
Is this resolved now? Or are you still having troubles?

**Comment by platzhersh** [comment]
Thanks a lot for all your insights so far. Still having troubles though:

```
04:25:09 worker3.1   |  [2020-06-06 04:25:09,881: ERROR/ForkPoolWorker-2] Task import_export_celery.tasks.run_export_job[ddaec139-d3d0-4b57-b112-da68d9ceb263] raised unexpected: TypeError('str() argument 2 must be str, not tuple',)
04:25:09 worker3.1   |  Traceback (most recent call last):
04:25:09 worker3.1   |    File "/path/to/project/.venv/lib/python3.6/site-packages/celery/app/trace.py", line 412, in trace_task
04:25:09 worker3.1   |      R = retval = fun(*args, **kwargs)
04:25:09 worker3.1   |    File "/path/to/project/.venv/lib/python3.6/site-packages/celery/app/trace.py", line 704, in __protected_call__
04:25:09 worker3.1   |      return self.run(*args, **kwargs)
04:25:09 worker3.1   |    File "/path/to/project/.venv/lib/python3.6/site-packages/import_export_celery/tasks.py", line 199, in run_export_job
04:25:09 worker3.1   |      class Resource(resource_class):
04:25:09 worker3.1   |  TypeError: str() argument 2 must be str, not tuple
```

when trying to use:

```
    # allow celery exports
    @classmethod
    def export_resource_classes(cls):
        return {
            'all rides': ('Ride resources', 'RideResource'),
        }
```

-> I used a string instead of a reference to try to avoid the "Models are not loaded yet" error. Which I would still get otherwise.

**Comment by platzhersh** [comment]
The problem is coming from the model and resource declaration in https://github.com/velafrica/velafrica-django/pull/87/files#diff-437b53c61a8ac4ddbcf042568378d893R250

**Comment by timthelion** [comment]
Rather than using a string reference try importing the resource in the `export_resource_classes` method.

**Comment by platzhersh** [comment]
Wow. That was it! After importing the Resource inside the `export_resource_classes`it worked!

Thank you so much!
